services:
  custom-n8n:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - N8N_VERSION=latest
    ports:
      - '80:5678'
    # command: ["tini", "--", "/docker-entrypoint.sh"]
